config/routes.rb
Rails.application.routes.draw do
   
   root 'pages#home'

   get '/home', to: 'pages#home'

   # get '/recipes' to: 'recipes#index'
   # get  '/recipes/new' to: 'recipes#new', as: 'new_recipe'

   resources :recipes do
     member do
      post 'like'
     end
   end

   resources :chefs, except: [:new]

   get'/register', to: 'chefs#new'

   #login routes
   get '/login', to: 'logins#new'
   post '/login', to: 'logins#create'
   get '/logout', to: 'logins#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ActiveRecord::Base
   has_many :recipes
   has_many :likes

   validates :chefs, presence: true, length: { minimum: 3, maximum: 40}
   validates :email, presence: true, length: { maximum: 105}

   has_secure_password
end

app/models/chefs.rb
class Chef < ActiveRecord::Base

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe

validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
   belongs_to :chef
   has_many :likes
   
   validates :chef_id, presence: true
   validates :name, presence: true
   validates :summary, presence: true
   validates :description, presence: true
   mount_uploader :picture, PictureUploader
   validate :picture_size
   default_scope -> { order(updated_at: :desc)}


   def thumbs_up_total
    self.likes.where(like: true).size
   end
   
   def thumbs_down_total
    self.likes.where(like: false).size
   end

   private
   def picture_size
      if picture.size > 5.megabytes
         errors.add(:picture, "should be less than 5 MegaBytes")
      end
   end 

   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
     !!current_user
  end 

  def require_user
   if !logged_in?
   	flash[:danger] = "You must be Log in"
   	redirect_to back
  end
 end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
    before_action :set_chef, only: [:edit, :update, :show]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update]

   def index
   @chefs = Chef.paginate(page: params[:page], per_page: 3)
   end
 
  def new
   @chef =Chef.new
  end

  def create
  	@chef =Chef.create(chef_params)
  	if @chef.save
    flash[:success] = "YOur Account has been successfully Created"
    session[:chef_id] = @chef.id
    redirect_to recipes_path

  	else render  'new' 
  	end
  end

   def edit

   end
  
  def update
    if @chef.update(chef_params)
   	   flash[:success] = "Your Profile has been updated succesfully"
       redirect_to chef_path(@chef)
    else 
    	render 'edit'
    end
  end

  def show
  @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
  end

 private
  def chef_params
   params.require(:chef).permit(:chefs, :email, :password)
  end


 def require_same_user
  if current_user != @chef
    flash[:danger]= 'You cant change  others chefs profile'
    redirect_to root_path
  end
 end

 def set_chef
  @chef = Chef.find(params[:id])
 end

end

app/controllers/logins_controller.rb
class LoginsController <ApplicationController


def new

end

def create

  chef =Chef.find_by(email: params[:email])
  if chef && chef.authenticate(params[:password])
    session[:chef_id] = chef.id
  	flash[:success] = 'You are Logged in'
  	redirect_to recipes_path

  else

  	flash.now[:danger] = 'Wrong email password combination'
  	render 'new'

  end
end

def destroy
	session[:chef_id] = nil
	flash[:success]='You have logged out'
	redirect_to root_path 

end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
       redirect_to recipes_path if logged_in?
    end


	end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_action :set_recipe, only: [:edit, :update, :show, :like]
   before_action :require_same_user, only: [:edit,:update]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 3)
  end

  def show
  end

  def new
  	@recipe = Recipe.new
  end

  def create
   @recipe =Recipe.new(recipe_params)
   @recipe.chef = current_user

   if @recipe.save
     flash[:success] = "Your Recipe was Successfully saved!!!"
       redirect_to recipes_path
   else
   	render :new
   end
  end

  def edit
  end

  def update
  		if @recipe.update(recipe_params)
  			flash[:success] = "Your Recipe is Updated Successfully!"
  			redirect_to recipe_path(@recipe)
  			#or either     
  			#redirect_to tecipe_path......it automatically redirect to  that particular recipe_path
  		else
  			render :edit
  		end

  end
  def like
  like=Like.create(like: params[:like],chef: current_user  , recipe: @recipe)
  if like.valid?
    if params[:like]=='true' ?  flash[:success]="Like" : flash[:success]="Dislike"
      redirect_to :back
    end
  else
    flash[:danger]="You Can Only  like/Dislike Only Once."
    redirect_to :back

  end
  end

  private
   def recipe_params
    params.require(:recipe).permit(:name,:summary,:description,:picture)
  end

  def set_recipe
  @recipe =Recipe.find(params[:id])
  end

  def require_same_user
   if current_user != @recipe.chef
    flash[:danger]='You can edit only your recipe'
    redirect_to recipes_path
  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(chef,options = {size: 80})
       gravatar_id = Digest::MD5::hexdigest(chef.email.downcase) 
       size = options[:size]
       gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
       image_tag(gravatar_url,alt: chef.chefs,class: "gravatar")
   end
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors' ,obj: @chef %>

  <div class ="row pull-center">
    <div class="well  col-md-12 col-md-offest-2">
       <%= form_for @chef do |f|%>
          <%= f.label :chefs %>
          <%= f.text_field :chefs %>

          <%= f.label :email%>
          <%= f.email_field :email%>

          <%= f.label :password %> 
          <%= f.password_field :password  %>

         

          <%=f.submit(@chef.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
       <% end %>   
    </div>	
  </div>

app/views/chefs/edit.html.erb
  <%= render "shared/page_title" ,title: 'Edit Your Account Details' %>

  <%= render 'form' %>

app/views/chefs/index.html.erb
 <%= render "shared/page_title" ,title: 'All Chefs' %>

<ul class="nav nav-tabs">
    <li class = 'active'>
        <%= link_to 'Chefs', chefs_path %>
    </li>
      <li>
        <%= link_to "Recipes", recipes_path %>
      </li>
  </ul>
    
  <div class = "row">
    <div class = "col-md-4 col-md-offset-4 center">
       <%= will_paginate %>
    </div>
  </div>

  <% @chefs.each do |chef| %>
    <div class = "row">
      <div class= "col col-md-4 col-md-offset-4 center">
        <%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
          <h4><em><%= chef.chefs %></em></h4>
      </div>
    </div>
  <% end %>

app/views/chefs/new.html.erb
   
   <%= render "shared/page_title" ,title: 'Register Now' %>

   <%= render 'form' %>

app/views/chefs/show.html.erb
 <%= render "shared/page_title" ,title: 'Chef:'+ @chef.chefs %>

  <div class = "row">
    <div class="col-md-4 col-md-offest-4 center">
      <%= gravatar_for @chef, size: 200 %>
      <hr/>
    </div>
   </div> 
   <hr/>

    <%= render "shared/page_title" ,title: 'Recipes belongs to him' %>


     <%= will_paginate @recipes %>


    <% @recipes.each do |recipe| %>
      <div class="row">
        <div class="col-md-2">
          
        </div>	

        <div class="col-md-6 well">
        	<%= link_to recipe.name, recipe_path(recipe) %>
        	<p><%= recipe.summary %></p>
          <p>
            <span class = "quiet"><em>Created:&nbsp<%= time_ago_in_words(recipe.created_at)  %></em>&nbsp ago</span>
          </p>
          <p>
            <span class = "quiet"><em>Updated:&nbsp<%= time_ago_in_words(recipe.updated_at)  %></em>&nbsp ago</span>
          </p>
           <div class="pull-right">
              <%= link_to like_recipe_path(recipe, like: true), method: :post do  %>
              <i class = "glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
              <% end %>&nbsp&nbsp&nbsp&nbsp
              <%= link_to like_recipe_path(recipe, like: false), method: :post do  %>
              <i class = "glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
              <% end %>
            </div>
        </div>
        <div class="col-md-4">
          <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar" ) if recipe.picture?  %>
        </div>

      </div>
    <% end %>

    <%= will_paginate  @recipes%>

app/views/layouts/_footer.html.erb
 <div class="footer">
    <p>&copy; MyRecipes 2016</p>
  </div>

app/views/layouts/_message.html.erb
<div class="row">
	<div class="col-md-10">
	  <% flash.each do |message_type,message| %>
	  <a class= "close" data-dismiss="alert">&#215;</a>
        <div class="alert alert-<%= message_type %>">
        <%= message %>
        
        </div>
	  <% end %>	
	</div>
</div>

app/views/layouts/_navigation.html.erb
<navbar class="navbar navbar-fixed-top navbar-default">
      <div class="container">
      	<%= link_to "Recipe App", home_path,class: "btn btn-log btn-success", id:"logo" %>
      	<div class="nav_item">
      		<%= link_to "link 1","",class: "btn btn-log btn-warning" %>
      	</div>

      	<div class="nav_item">
      		<%= link_to "link 2","",class: "btn btn-log btn-warning" %>
      	</div>

            <% if logged_in? %>
      	<div class="nav_item">
      		<%= link_to "New Recipe", new_recipe_path ,class: "btn btn-log btn-warning" %>
      	</div>
            

            <ul class="nav_item">
               <li class="dropdown">
                 <%= link_to '#', class:"btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
                 <% current_user.chefs %> <b class ="caret" ></b>
                 <% end %>
                  <ul class= "dropdown-menu">
                    <li><%= link_to 'View Profile', chef_path(current_user) %></li>
                    <li><%= link_to 'Edit Profile', edit_chef_path(current_user) %></li>
                    <li class= "divider" ></li>
                    <li><%= link_to "logout", logout_path %></li>
                  </ul>
               </li>
            </ul>
            <% else %>
            <div class="nav_item">
                  <%= link_to "Log In", login_path ,class: "btn btn-log btn-success" %>
            </div>
            <% end %>

      </div>
    </navbar>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipeapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>
    <div class="container">
     <%=render 'layouts/message' %>
    <%= yield %>
    </div>
     <%= render 'layouts/footer' %>  
   
</html>

app/views/logins/destroy.html.erb
destroy.html.erb

app/views/logins/new.html.erb
<% if !logged_in? %>
<%= render 'shared/page_title', title: 'Log In' %>

<div class = "row">
  <div class = "well col-md-6 col-md-offset-3">
   <%= form_tag '/login' do %>
      <%= label_tag :email %>
      <%= text_field_tag :email %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= submit_tag 'Login', class: 'btn btn-success' %>


    <% end %>
  </div>  
</div>
<% else   %>
<%= render 'shared/page_title', title: 'Already Logged in ' %>
<% end %>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to MyReceipe APP</h1>

	<h2>
		This is the Second Home Page
	</h2>
   <p>	<%= link_to "Sign Up?",register_path,class: "btn btn-large btn-success" %> </p>
</div>

<div class="row">
	<div class="cl-lg-4">
	  <h3 class="midraw well">
	  	View Receipes as Guest User
	  </h3>
		<h2 class="left">Browse and View Receipies as Guest and Sign Up Later</h2>
		<p><%= link_to "Browse Receipes Listings", recipes_path, class: "btn btn-info btn-small" %></p>
	</div>
	<div class="cl-lg-4">
	  <h3 class="midraw well">
	  	View Receipes as Guest User
	  </h3>
		<h2 class="left">Add Update your recipes/create reviews/Like-Dislikes Recipes </h2>
		<p><%= link_to "Login to your account", login_path , class: "btn btn-info btn-small" %></p>
	</div>
	<div class="cl-lg-4 ">
	  <h3 class="midraw">
	  	View Receipes as Guest User
	  </h3>
		<h2 class="left well">Browse and View Receipies as Guest User</h2>
		<p><%= link_to "Browse Receipes Listings", "", class: "btn btn-info btn-small" %></p>
	</div>


</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors' ,obj: @recipe %>

  <div class ="row pull-center">
    <div class="well  col-md-12 col-md-offest-2">
       <%= form_for(@recipe, html: { multipart: true}) do |f|%>
          <%= f.label :name %>
          <%= f.text_field :name %>

          <%= f.label :summary %>
          <%= f.text_field :summary%>

          <%= f.label :description %> 
          <%= f.text_area :description, rows:10 %>

          <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
          </span>

          <%=f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
       <% end %>   
    </div>	
  </div>

  <script type="text/javascript">
  $('#recipe_picture').bind('change', function(){
  size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 5){
    alert('Maximum file size is 5MB, PLease choose a smaller image');
  }
  })
  </script>

app/views/recipes/edit.html.erb
 
  <%= render "shared/page_title" ,title: 'Edit Recipe'%>

  <%= render 'form' %>

app/views/recipes/index.html.erb
  <%= render "shared/page_title" ,title: 'All Recipes'%>

  <ul class="nav nav-tabs">
    <li class = 'active'>
       <%= link_to "Recipes", recipes_path %>
    </li>
    <li>
    <%= link_to 'chefs', chefs_path %>
  </li>
  </ul>
  
  
  <%= will_paginate %>


    <% @recipes.each do |recipe| %>
      <div class="row">
        <div class="col-md-2">
           <section  class="chef_info center">
           	<%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
            <h5>Chef.name <%= recipe.chef.chefs%></h5>
           </section>
           <hr/>
        </div>	

        <div class="col-md-6 well">
        	<%= link_to recipe.name, recipe_path(recipe) %>
        	<p><%= recipe.summary %></p>
          <p>
            <span class = "quiet"><em>Created:&nbsp<%= time_ago_in_words(recipe.created_at)  %></em>&nbsp ago</span>
          </p>
          <p>
            <span class = "quiet"><em>Updated:&nbsp<%= time_ago_in_words(recipe.updated_at)  %></em>&nbsp ago</span>
          </p>
           <div class="pull-right">
              <%= link_to like_recipe_path(recipe, like: true), method: :post do  %>
              <i class = "glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
              <% end %>&nbsp&nbsp&nbsp&nbsp
              <%= link_to like_recipe_path(recipe, like: false), method: :post do  %>
              <i class = "glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
              <% end %>
            </div>
        </div>
        <div class="col-md-4">
          <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar" ) if recipe.picture?  %>
        </div>

      </div>
    <% end %>

    <%= will_paginate %>

app/views/recipes/new.html.erb
 
   <%= render "shared/page_title" ,title: 'Create a new Recipe' %>

  <%= render 'form'%>

app/views/recipes/show.html.erb
    

    <p> recipe name is <%= @recipe.name %> </p>

 <div class = "row">
   <div class="col-md-4 pull-right center">
     <%=link_to (gravatar_for @recipe.chef, size: 200),chef_path(@recipe.chef) %>
     <p>
     	<h5>Brought to you by: <%= @recipe.chef.chefs%></h5>
     </p>
   </div>
     <div class = "col-md-8">
       <h3><%= @recipe.summary%></h3>
         <div class = "show_picture">
          <%= image_tag(@recipe.picture.url,class: "gravatar") if @recipe.picture? %>
         </div>
         <div class= "well">
          <p>
            <strong>Steps:</strong>
          </p>   	
            <%= simple_format(@recipe.description) %>
            <div class="pull-right">
              <%= link_to like_recipe_path(@recipe, like: true), method: :post do  %>
              <i class = "glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
              <% end %>&nbsp&nbsp&nbsp&nbsp
              <%= link_to like_recipe_path(@recipe, like: false), method: :post do  %>
              <i class = "glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
              <% end %>
            </div>
         </div> 
    </div>
 </div>
     <% if logged_in? and @recipe.chef == current_user %>
     <h4> <%= link_to "Edit This Reipe",edit_recipe_path,class: "btn btn-success" %></h4>
     <% end %>
     <h5> <%= link_to "Return to Recipes Menu",recipes_path,class: "btn btn-warning btn-small" %> </h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please Correct the following Errors</h5>
        <ul>
  	      <%  obj.errors.full_messages.each do |msg| %>
  	        <li> <%= msg %> </li> 
  	         <% end %>
        </ul>
    </div>
  </div>      
<% end %>

  <br />

app/views/shared/_page_title.html.erb
<h1><%= title %></h1>
 <hr/>